sudo: required
group: deprecated-2017Q3
language: scala
scala:
- 2.11.11
services:
- docker
before_install:
- "./tools/travis/setup.sh"
install: true
script:
- "./tools/travis/build.sh && ./tools/travis/deploy.sh && ./tools/travis/test.sh"
deploy:
- provider: script
  script: "./tools/travis/publish.sh ibmfunctions ${TRAVIS_TAG%@*} ${TRAVIS_TAG##*@}"
  on:
    tags: true
    all_branches: true
- provider: script
  script: "./tools/travis/publish.sh ibmfunctions kotlin latest"
  on:
    branch: master
env:
  global:
  - secure: Lyi4LKGG/qgVy0nfma4YYjOgCHzUYY6NG1q+G9UdkZ/lzLZ28BUOyC+uZrHBpQgYojUPRt3es6wxDuUOjYlJWXjyyTnxBwTKTkhwLGViXKYXsqmSI+ZXUTMe51+0ZVz13pHo6NF4t6ZgO8yAoJT492cCoXWyFwRScdjMPSHvVLMaxptiD7pOtM3To8BqM+sZASm/8vLLRHVxwo2surV69b5l9NqSp86qQUsvjqd1BFNJvJXTTvdznY4PSDv1e1qRBZHQszPyTt5XwLGb64acVzKGn4P5ducDtPoQLQ3HrHyEHjg8ybzao47TvJ6ch1D99uD5OibnrjB1RDyemg9AZBIRr9De+8/Lc2dO2fITcDqdgUSr9JI/fv9lb4LxcITtJ5j6I1Zuj5uvgghc4VSYxf6Ixko9a9mV6mWR5rUtPM0QhxZEFZbpt/I70iyrTDJLJH+Vcb3+IrkGCB/f/JZh7occaxs1sbEWQgF/5Dc4CbHVgrbs5Bj0CL1oQcg496a9fsUlOQ28kyRI1H16Ea5Qhq5Dq/4euV+buxTk42HhL0+qbNiWRueXQhBw6ZayXSx0r0gEGGtfdOpbeMP4ZfIDT77qVc1NycWpr5Pln0qj0eH96zvA/BPSHEwPj2yWhHqzLle9jsq4eKF7e77OYLeRjcwsBcf8pLyl4k1i3BU26Bk=
  - secure: m8Lj6ZyTCH4jnGiWmTqS3GV7EimjM8QiwPsJ4tKSzfPj0ZXuEM/4IYQxMRIHhTnW8R1ANHXmcOUn1oL0QFMNFMUY2kjMQZM+AXvlHmrmrAI64OSSRyVS0GyjGM1raJ+JsvodOIs1njXRmesSKpmksoJBuOEzlFF/uFRMpr5ZE+0+7SQfm5ec/VkyHnTqESNo5h/0hJnnWtMzQ66bR75WpVxUYF8tQcWmcg8vHnKQVwrAGi41Z4wlRnHd4WVnJtR4KL6bcwhfYyZAW+UsvLzO8zGd6gO4iMwILnb6oBg/PYL1bKbRpqs3ZgN59ajRWiYW8zYt/z3iOYUqaSjUjxGa4V2i5dPDnAZWT+b0P58Qh2qhY8lfNthrzhGeqlVONOdUBbzomX2Kl+cQJyy5tq0sKch60ZpgagSSkzWniG+snla/nKuYV4Ka5pY9FDMCCZHN7uNbY4eHj5PRAGnD0pr0I4aCssM9Ip5mErqgIU4i2D1iG1H7ypPng8vaVn6P4HUQZ4AZTCitdNc4cfeGHo+h3jGYiEXA5BgsBXcVBIQmHUp3/LgIgL3+YHE5ztuT9XLT8LZ12e2dUq6lj2zXrcV1DpjqIgAEktw3VbDSDUQsqYLt9puZpo8u04hey8PBlz+zmrN7/U5KGUlLqPaOUhELbFt9rPu+RuE875v9qZBWJbU=
